# version: '3.8'   #Comento esta linea porque estaba tirando un error de versión

services:
  # Base de datos PostgreSQL (Donde inyectamos kairos_db)
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    restart: unless-stopped

  # Base de datos MySQL (Donde inyectamos sigct_rural)
  db-mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: unless-stopped

  # Tus servicios locales configurados para Docker
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: sigct_backend
    volumes:
      - ./src/backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - db-mysql

  ai_service:
    build:
      context: ./src/ai_models
      dockerfile: Dockerfile
    container_name: sigct_ai_service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: sigct_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend