// Catálogo declarativo de señales S01..S80
// Fuente: CMSC_SIGNAL_MAP_v1.md (Documentacion/Arquitectura)
// Materializado como rama declarativa del registro, en modo lectura.
// Los estados respetan el canon único de honestidad:
// REAL · REAL-LOCAL · SIM · DISENO · ROTO · HUERFANO · REF

export const SIGNAL_CATALOG = [
  { signal_id: 'S01', name: 'Envelope V3', clase_senal: 'REAL', dominio: 'Digitales', estado: 'REAL', origen: 'Backend API v3', cadencia: 'por petición', puerto: 'P-BE-01', consumidores: 'Dashboard', metadata_ref: 'SIGNAL_MAP 1.1', confianza: null, nota: 'Dashboard.jsx' },
  { signal_id: 'S02', name: 'Serie temporal del grafico', clase_senal: 'REAL', dominio: 'Digitales', estado: 'REAL', origen: 'Derivada de V3', cadencia: 'por petición', puerto: 'P-BE-01', consumidores: 'Dashboard', metadata_ref: 'SIGNAL_MAP 1.1', confianza: null, nota: 'Dashboard.jsx' },
  { signal_id: 'S03', name: 'Clima externo Open-Meteo', clase_senal: 'REMOTA', dominio: 'Físicas', estado: 'REAL-LOCAL', origen: 'API externa Open-Meteo', cadencia: 'forecast por hora', puerto: 'P-WEATHER-01', consumidores: 'Cruda clima-externo', metadata_ref: 'SIGNAL_MAP 1.1', confianza: null, nota: 're-etiquetada clima-externo, NO telemetría rural' },
  { signal_id: 'S04', name: 'Cluster BBB health', clase_senal: 'SIMULADA', dominio: 'Digitales', estado: 'SIM', origen: 'health backend + métricas fabricadas', cadencia: 'por petición', puerto: 'P-BE-01', consumidores: 'TopNav, Dashboard', metadata_ref: 'SIGNAL_MAP 1.1', confianza: null, nota: 'saneo R2 etiquetado SIM, jamás como real' },
  { signal_id: 'S05', name: 'Badge LIVE derivado', clase_senal: 'GENERADA', dominio: 'Lógicas', estado: 'REAL', origen: 'source_mode del envelope', cadencia: 'por estado', puerto: null, consumidores: 'Dashboard', metadata_ref: 'SIGNAL_MAP 1.1', confianza: null, nota: 'no verifica sensor físico' },
  { signal_id: 'S06', name: 'Contador docs research_v2', clase_senal: 'GENERADA', dominio: 'Documentales', estado: 'REAL', origen: 'registry generado', cadencia: 'por build', puerto: 'P-KH-01', consumidores: 'Dashboard', metadata_ref: 'SIGNAL_MAP 1.1', confianza: null, nota: 'conteo real del registry' },
  { signal_id: 'S10', name: 'SensorReading.temperature', clase_senal: 'REAL', dominio: 'Físicas', estado: 'REAL', origen: 'HTTP V3 persistida', cadencia: 'por ingesta', puerto: 'P-BE-01', consumidores: 'Dashboard, DataScience, voz', metadata_ref: 'SIGNAL_MAP 3 S10', confianza: null, nota: 'envelope ' },
  { signal_id: 'S11', name: 'SensorReading.humidity', clase_senal: 'REAL', dominio: 'Físicas', estado: 'REAL', origen: 'HTTP V3 persistida', cadencia: 'por ingesta', puerto: 'P-BE-01', consumidores: 'Dashboard, DataScience, voz', metadata_ref: 'SIGNAL_MAP 3 S11', confianza: null, nota: 'envelope ' },
  { signal_id: 'S12', name: 'sensor_id + timestamp', clase_senal: 'REAL', dominio: 'Digitales', estado: 'REAL', origen: 'SensorReading', cadencia: 'por lectura', puerto: 'P-BE-01', consumidores: 'traza', metadata_ref: 'SIGNAL_MAP 1.2', confianza: null, nota: 'metadata de la lectura' },
  { signal_id: 'S13', name: 'Datos sintéticos V1/V2', clase_senal: 'SIMULADA', dominio: 'Físicas', estado: 'SIM', origen: 'síntesis sin filas', cadencia: 'por lectura', puerto: 'P-BE-01', consumidores: 'Telemetría', metadata_ref: 'SIGNAL_MAP 1.2', confianza: null, nota: 'genera solo si no hay filas' },
  { signal_id: 'S14', name: 'Envelope source_mode', clase_senal: 'REAL', dominio: 'Lógicas', estado: 'REAL', origen: 'ruta del envelope V3', cadencia: 'por lectura', puerto: 'P-BE-01', consumidores: 'badges', metadata_ref: 'SIGNAL_MAP 1.2', confianza: null, nota: 'live · simulated · fallback' },
  { signal_id: 'S15', name: 'LabSignal evento de dominio', clase_senal: 'REAL', dominio: 'Digitales', estado: 'REAL', origen: 'event bus en memoria', cadencia: 'por lectura persistida', puerto: 'P-BE-01', consumidores: 'LaboratorioService agricultura', metadata_ref: 'SIGNAL_MAP 1.2', confianza: null, nota: 'inmutable, in-process' },
  { signal_id: 'S20', name: 'Fisiología UBTN', clase_senal: 'LOCAL', dominio: 'Biológicas', estado: 'DISENO', origen: 'sensores UBTN propuestos', cadencia: 'diseño', puerto: null, consumidores: 'UBTN', metadata_ref: 'SIGNAL_MAP 1.3', confianza: null, nota: '0% código' },
  { signal_id: 'S21', name: 'Catálogo sensores UBTN', clase_senal: 'LOCAL', dominio: 'Biológicas', estado: 'DISENO', origen: 'ADS1292R, MAX30102, IMU', cadencia: 'diseño', puerto: null, consumidores: 'UBTN', metadata_ref: 'SIGNAL_MAP 1.3', confianza: null, nota: 'A-7 pendiente' },
  { signal_id: 'S22', name: 'MQTT UBTN', clase_senal: 'REMOTA', dominio: 'Digitales', estado: 'DISENO', origen: 'broker MQTT 5 propuesto', cadencia: 'diseño', puerto: null, consumidores: 'UBTN', metadata_ref: 'SIGNAL_MAP 1.3', confianza: null, nota: 'sin broker en compose' },
  { signal_id: 'S23', name: 'Contrato lectura UBTN', clase_senal: 'GENERADA', dominio: 'Lógicas', estado: 'DISENO', origen: 'especificación de contrato', cadencia: 'diseño', puerto: null, consumidores: 'UBTN', metadata_ref: 'SIGNAL_MAP 1.3', confianza: null, nota: 'reading_signature y flags' },
  { signal_id: 'S24', name: 'Ráfagas ECG/PPG', clase_senal: 'LOCAL', dominio: 'Biológicas', estado: 'DISENO', origen: 'object storage propuesto', cadencia: 'diseño', puerto: null, consumidores: 'UBTN', metadata_ref: 'SIGNAL_MAP 1.3', confianza: null, nota: 'bursts en storage' },
  { signal_id: 'S25', name: 'Firmware BBB/ESP32', clase_senal: 'GENERADA', dominio: 'Digitales', estado: 'DISENO', origen: 'scripts embebidos', cadencia: 'diseño', puerto: null, consumidores: 'Embedded', metadata_ref: 'SIGNAL_MAP 1.3', confianza: null, nota: 'archivos de 0 bytes' },
  { signal_id: 'S30', name: 'FFT micrófono Telecom', clase_senal: 'LOCAL', dominio: 'Acústicas', estado: 'REAL-LOCAL', origen: 'WebAudio AnalyserNode', cadencia: '44.1 kHz, frame navegador', puerto: 'P-LAB-02', consumidores: 'TelecomLab', metadata_ref: 'SIGNAL_MAP 3 S30', confianza: null, nota: 'única acústica real con DSP local' },
  { signal_id: 'S31', name: 'Bandas RF WebSDR', clase_senal: 'REMOTA', dominio: 'RF', estado: 'REAL-LOCAL', origen: 'WebSDR externo', cadencia: 'vivo', puerto: null, consumidores: 'TelecomLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'ifirame encapsulado' },
  { signal_id: 'S32', name: 'Voltaje y corriente de circuitos', clase_senal: 'SIMULADA', dominio: 'Físicas', estado: 'SIM', origen: 'Falstad + solver Python local', cadencia: 'por simulación', puerto: 'P-LAB-01', consumidores: 'ElectronicsLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'simulación, no medición' },
  { signal_id: 'S33', name: 'Electrónica sintética backend', clase_senal: 'SIMULADA', dominio: 'Físicas', estado: 'SIM', origen: 'electronics_strategy', cadencia: 'por petición', puerto: 'P-LAB-01', consumidores: 'ElectronicsLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'voltaje, corriente, temperatura' },
  { signal_id: 'S34', name: 'Telecom sintética', clase_senal: 'SIMULADA', dominio: 'RF', estado: 'SIM', origen: 'telecom_strategy', cadencia: 'por petición', puerto: 'P-LAB-02', consumidores: 'TelecomLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'frecuencia dominante, SNR, ruido' },
  { signal_id: 'S35', name: 'Series Fourier y Wavelets', clase_senal: 'SIMULADA', dominio: 'Matemáticas', estado: 'SIM', origen: 'Motor de Modelado Científico (MMC)', cadencia: 'interactiva', puerto: null, consumidores: 'AdvancedMathLabV2', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'fase portrait incluido' },
  { signal_id: 'S36', name: 'Señales de useLabStore', clase_senal: 'SIMULADA', dominio: 'Digitales', estado: 'SIM', origen: 'mochila federada', cadencia: 'por navegación', puerto: 'P-LAB-01', consumidores: 'labs', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'híbrido sim + metadata falstad' },
  { signal_id: 'S37', name: 'Osciloscopio y THD', clase_senal: 'SIMULADA', dominio: 'Matemáticas', estado: 'SIM', origen: 'PhysicsLab', cadencia: 'por simulación', puerto: 'P-LAB-01', consumidores: 'ElectronicsLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'forma de onda analizada' },
  { signal_id: 'S38', name: 'Esquema JSON SchematicEditor', clase_senal: 'LOCAL', dominio: 'Digitales', estado: 'REAL-LOCAL', origen: 'archivo del usuario', cadencia: 'por edición', puerto: 'P-LAB-01', consumidores: 'ElectronicsLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'entrada real de archivo' },
  { signal_id: 'S39', name: 'Embebidos externos', clase_senal: 'REMOTA', dominio: 'Matemáticas', estado: 'REF', origen: 'Wokwi, Plotly, Pyodide', cadencia: 'por uso', puerto: null, consumidores: 'EmbeddedLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'referencia externa encapsulada' },
  { signal_id: 'S40', name: 'Consola DataScience SSE', clase_senal: 'LOCAL', dominio: 'Digitales', estado: 'ROTO', origen: 'Pyodide, endpoint cloud deprecado', cadencia: 'por uso', puerto: null, consumidores: 'DataScienceLab', metadata_ref: 'SIGNAL_MAP 1.4', confianza: null, nota: 'parcialmente roto, endpoint sin SSE' },
  { signal_id: 'S50', name: 'RobotTelemetry', clase_senal: 'REAL', dominio: 'Mecánicas', estado: 'ROTO', origen: 'API persistida', cadencia: '1 Hz sim, sin evidencia física', puerto: 'P-LAB-03', consumidores: 'RoboticsLab', metadata_ref: 'SIGNAL_MAP 3 S50', confianza: null, nota: 'backend REAL; cliente frontend apunta a localhost:8000' },
  { signal_id: 'S51', name: 'Trayectoria helicoidal sintética', clase_senal: 'SIMULADA', dominio: 'Mecánicas', estado: 'SIM', origen: 'physics_sim.py', cadencia: '1 POST por segundo', puerto: 'P-LAB-03', consumidores: 'RoboticsLab', metadata_ref: 'SIGNAL_MAP 1.5', confianza: null, nota: 'simulación de trayectoria' },
  { signal_id: 'S52', name: 'RobotCommand', clase_senal: 'REAL', dominio: 'Lógicas', estado: 'REAL', origen: 'ViewSet autenticado', cadencia: 'por comando', puerto: 'P-LAB-03', consumidores: 'back autenticado', metadata_ref: 'SIGNAL_MAP 1.5', confianza: null, nota: 'API real' },
  { signal_id: 'S53', name: 'Métricas aleatorias de robótica', clase_senal: 'SIMULADA', dominio: 'Mecánicas', estado: 'SIM', origen: 'hooks de frontend', cadencia: 'por render', puerto: null, consumidores: 'RoboticsLab', metadata_ref: 'SIGNAL_MAP 1.5', confianza: null, nota: 'aleatorio, no medición' },
  { signal_id: 'S54', name: 'Robotics strategy backend', clase_senal: 'SIMULADA', dominio: 'Físicas', estado: 'SIM', origen: 'robotics_strategy', cadencia: 'por petición', puerto: 'P-LAB-03', consumidores: 'RoboticsLab', metadata_ref: 'SIGNAL_MAP 1.5', confianza: null, nota: 'dominio simulado v2' },
  { signal_id: 'S60', name: 'Imagen hoja 224x224', clase_senal: 'REAL', dominio: 'Imágenes', estado: 'REAL', origen: 'archivo multipart', cadencia: 'bajo demanda', puerto: 'P-IA-01', consumidores: 'AIPredictiva', metadata_ref: 'SIGNAL_MAP 1.6', confianza: null, nota: 'entrada real de imagen' },
  { signal_id: 'S61', name: 'Inferencia /infer', clase_senal: 'IA', dominio: 'IA', estado: 'REAL', origen: 'FastAPI 8081', cadencia: 'por request', puerto: 'P-IA-01', consumidores: 'AIPredictiva', metadata_ref: 'SIGNAL_MAP 1.6', confianza: null, nota: 'diagnosis, class_index, confidence' },
  { signal_id: 'S62', name: 'Voz del asistente', clase_senal: 'IA', dominio: 'Acústicas', estado: 'REAL', origen: 'MediaRecorder a /assist', cadencia: 'por comando', puerto: 'P-IA-01', consumidores: 'VoiceAssistant', metadata_ref: 'SIGNAL_MAP 3 S62', confianza: null, nota: 'STT Google, TTS gTTS, confianza 0.9/0.8/0.5 por intent' },
  { signal_id: 'S63', name: 'SSE infer log', clase_senal: 'IA', dominio: 'Documentales', estado: 'REAL', origen: 'tail de infer_log.jsonl', cadencia: 'por evento', puerto: 'P-IA-01', consumidores: 'evidencia', metadata_ref: 'SIGNAL_MAP 1.6', confianza: null, nota: 'registro real de inferencias' },
  { signal_id: 'S64', name: 'Análisis de circuito determinista', clase_senal: 'IA', dominio: 'Digitales', estado: 'REAL', origen: 'reglas FastAPI', cadencia: 'por petición', puerto: 'P-IA-01', consumidores: 'ElectronicsLab', metadata_ref: 'SIGNAL_MAP 1.6', confianza: null, nota: 'sin ML, respuestas por reglas' },
  { signal_id: 'S65', name: 'Conversación con umbrales', clase_senal: 'IA', dominio: 'IA', estado: 'REAL', origen: 'memoria en proceso + umbrales', cadencia: 'por consulta', puerto: 'P-IA-01', consumidores: 'voz', metadata_ref: 'SIGNAL_MAP 1.6', confianza: null, nota: 'temp mayor 30, hum menor 30 sobre SensorReading' },
  { signal_id: 'S66', name: 'ASR con fallback silencioso', clase_senal: 'IA', dominio: 'Acústicas', estado: 'REAL', origen: 'imports condicionales', cadencia: 'por uso', puerto: 'P-IA-01', consumidores: 'VoiceAssistant', metadata_ref: 'SIGNAL_MAP 1.6', confianza: null, nota: 'real limitado' },
  { signal_id: 'S70', name: 'Dataset agrícola v1', clase_senal: 'GENERADA', dominio: 'Imágenes', estado: 'REF', origen: '22.488 imgs, 16 clases, 3 especies', cadencia: 'estático congelado', puerto: null, consumidores: 'benchmark', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'dataset_card.md' },
  { signal_id: 'S71', name: 'Split congelado', clase_senal: 'GENERADA', dominio: 'Documentales', estado: 'REF', origen: '15.741/3.373/3.374 seed 42', cadencia: 'estático', puerto: null, consumidores: 'benchmark', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'sin fugas por SHA-256' },
  { signal_id: 'S72', name: 'M1 MobileNetV2 baseline', clase_senal: 'HISTORICA', dominio: 'IA', estado: 'REF', origen: 'entrenamiento 16 clases', cadencia: 'congelado', puerto: null, consumidores: 'gobernanza', metadata_ref: 'SIGNAL_MAP 1.7', confianza: 0.9899, nota: 'macro-F1; artefactos no reconstruibles en disco' },
  { signal_id: 'S73', name: 'M2 EfficientNet-B0 challenger', clase_senal: 'EXPERIMENTAL', dominio: 'IA', estado: 'REF', origen: 'corrida oficial 2026-09-27', cadencia: 'congelado', puerto: null, consumidores: 'gobernanza', metadata_ref: 'SIGNAL_MAP 1.7', confianza: 0.9937, nota: 'macro-F1; gates PASS; decisión pendiente' },
  { signal_id: 'S74', name: 'Modelo productivo degenerado', clase_senal: 'IA', dominio: 'Imágenes', estado: 'ROTO', origen: 'plant_disease_mbv2.h5', cadencia: 'no productivo', puerto: 'P-IA-01', consumidores: 'AIPredictiva', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'colapsa a class_0, descalificado' },
  { signal_id: 'S75', name: 'Líneas research_v2', clase_senal: 'GENERADA', dominio: 'Documentales', estado: 'DISENO', origen: 'programa de investigación', cadencia: 'diseño', puerto: null, consumidores: 'gobernanza', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: '7 líneas, agricultura ejecutada' },
  { signal_id: 'S76', name: 'Modelos de series diseño', clase_senal: 'GENERADA', dominio: 'IA', estado: 'DISENO', origen: 'Prophet, ARIMA, LSTM, TFT', cadencia: 'diseño', puerto: null, consumidores: 'Telemetry AI', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'no entrenados' },
  { signal_id: 'S77', name: 'Bioacústica diseño', clase_senal: 'GENERADA', dominio: 'Acústicas', estado: 'DISENO', origen: 'CNN/CRNN, MFCC, espectrogramas', cadencia: 'diseño', puerto: null, consumidores: 'Audio Intelligence', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'bovinos, porcinos, aves, abejas' },
  { signal_id: 'S78', name: 'Signal Intelligence diseño', clase_senal: 'GENERADA', dominio: 'Espectrales', estado: 'DISENO', origen: 'wavelets vs FFT, change points', cadencia: 'diseño', puerto: null, consumidores: 'Signal Intelligence', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'Lab espectral Fase 2' },
  { signal_id: 'S79', name: 'Documentos del Knowledge Hub', clase_senal: 'REAL', dominio: 'Documentales', estado: 'REAL', origen: 'registry generado en build', cadencia: 'por build', puerto: 'P-KH-01', consumidores: '/knowledge', metadata_ref: 'SIGNAL_MAP 3 S79', confianza: null, nota: '51 docs, 6 categorías, 18 research_v2' },
  { signal_id: 'S80', name: 'Manifiestos YAML', clase_senal: 'HISTORICA', dominio: 'Documentales', estado: 'REF', origen: 'docs/ai/manifests', cadencia: 'estático', puerto: null, consumidores: 'gobernanza', metadata_ref: 'SIGNAL_MAP 1.7', confianza: null, nota: 'deriva referencial v1/v2 a reconciliar' }
];

export const LIVE_SIGNAL_IDS = ['S10', 'S11', 'S03', 'S30'];

export const SANE_ENTRIES = [
  { signal_id: 'S04', name: 'Cluster BBB', estado: 'SIM', nota: 'métricas de health y fabricadas; etiqueta SIM, jamás real' },
  { signal_id: 'S50', name: 'RobotTelemetry', estado: 'ROTO', nota: 'cliente frontend apunta a localhost:8000; backend real en 8010; corrección fuera del slice' }
];

export const HUERFANO_ENTRY = {
  signal_id: 'BRIDGE',
  name: 'bridgeStatus del useLabStore',
  estado: 'HUERFANO',
  nota: 'existe y funciona, sin conexión al ecosistema; congelado y etiquetado, no borrado'
};