"""
Django settings for sigct_backend project.

Generated by 'django-admin startproject' using Django.
Modified for SIGC&T Rural: Soporte Multi-Entorno (Docker/Local MySQL/Local Postgres).
"""

import os
from pathlib import Path
import dj_database_url  # Vital para leer la configuración de BD dinámicamente

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# 1. SEGURIDAD Y CONFIGURACIÓN BÁSICA
# ==============================================================================

# ADVERTENCIA: Mantén la secret key secreta en producción.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-sigct-rural-2025')

# DEBUG debe ser False en producción
DEBUG = True

ALLOWED_HOSTS = ['*']  # Permite acceso desde Docker, Localhost y Red Local

# ==============================================================================
# 2. APLICACIONES INSTALADAS
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de terceros
    'rest_framework',
    'corsheaders',  # Manejo de CORS para comunicación con React
    
    # Aplicaciones del Proyecto (Tus módulos)
    'api',          # Tu lógica de negocio principal
    'users',        # Tu gestión de usuarios
    'ai_service',   # Integración futura con IA
]

# ==============================================================================
# 3. MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ¡CRÍTICO! Debe ir arriba para que React funcione
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sigct_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigct_backend.wsgi.application'

# ==============================================================================
# 4. LÓGICA DE BASE DE DATOS (EL CEREBRO HÍBRIDO)
# ==============================================================================

# PASO 1: Definimos una base por defecto (SQLite) para que Django no se rompa si no configuras nada.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PASO 2: Intentamos configurar una BD Real (MySQL Local o Postgres Local/Docker)
# La variable DATABASE_URL tiene el formato: motor://usuario:password@host:puerto/nombre_db

# Verificamos si existe la variable (Docker la inyecta automáticamente)
database_url = os.environ.get('DATABASE_URL')

if database_url:
    # CASO A: Estamos en Docker (o definiste la variable en tu PC para usar Postgres Local)
    DATABASES['default'] = dj_database_url.config(
        default=database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
else:
    # CASO B: Estás en tu PC local y NO definiste variable de entorno.
    # Aquí puedes "descomentar" si quieres usar tu MySQL local "a la fuerza".
    
    # --- BLOQUE PARA TU MYSQL LOCAL (Descomenta y ajusta si lo deseas) ---
    # DATABASES['default'] = {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'sigct_rural',     # Nombre de tu BD en MySQL Workbench
    #     'USER': 'root',            # Tu usuario local
    #     'PASSWORD': 'tu_password', # Tu contraseña local
    #     'HOST': 'localhost',       # O '127.0.0.1'
    #     'PORT': '3306',
    # }
    pass

# ==============================================================================
# 5. VALIDACIÓN DE CONTRASEÑAS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    # { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    # { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    # { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    # { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# ==============================================================================
# 6. INTERNACIONALIZACIÓN Y ZONA HORARIA
# ==============================================================================

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# 7. ARCHIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'  # Usar al desplegar en producción

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# 8. CONFIGURACIÓN CORS (INTEGRACIÓN FRONTEND)
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = True  # Desarrollo: Permitir todo