"""
Django settings for sigct_backend project.

Generated by 'django-admin startproject' using Django.
Modified for SIGC&T Rural: Soporte Multi-Entorno (Docker/Postgres prioritario).
"""

import os
from pathlib import Path
import dj_database_url  # Vital para leer la configuración de BD dinámicamente
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent
load_dotenv(PROJECT_ROOT / '.env')

# ==============================================================================
# 1. SEGURIDAD Y CONFIGURACIÓN BÁSICA
# ==============================================================================

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-sigct-rural-2025')
DEBUG = True
ALLOWED_HOSTS = ['*']

# ==============================================================================
# 2. APLICACIONES INSTALADAS
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de terceros
    'rest_framework',
    'corsheaders', 
    
    # Aplicaciones del Proyecto
    'api', 
    'users',
]

# ==============================================================================
# 3. MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sigct_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigct_backend.wsgi.application'

# ==============================================================================
# 4. LÓGICA DE BASE DE DATOS (MIGRACIÓN A POSTGRESQL)
# ==============================================================================

# Verificamos si existe la variable DATABASE_URL (Docker la inyecta automáticamente)
database_url = os.environ.get('DATABASE_URL')

if database_url:
    # CASO A: Entorno Docker con PostgreSQL (Solvencia Técnica)
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # CASO B: Entorno Local (Git Bash / Terminal)
    # Si no hay URL, usamos la configuración manual de Postgres local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'sigct_db'),
            'USER': os.environ.get('DB_USER', 'user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'password'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# ==============================================================================
# 5. VALIDACIÓN DE CONTRASEÑAS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = []

# ==============================================================================
# 6. INTERNACIONALIZACIÓN Y ZONA HORARIA
# ==============================================================================

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# 7. ARCHIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# 8. CONFIGURACIÓN CORS (INTEGRACIÓN FRONTEND)
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = True