"""
Django settings for sigct_backend project.

Generated by 'django-admin startproject' using Django.
Modified for SIGC&T Rural: Soporte Multi-Entorno (Docker/Postgres prioritario).
"""

import os
from pathlib import Path
import dj_database_url  # Vital para leer la configuración de BD dinámicamente
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent
load_dotenv(PROJECT_ROOT / '.env')

# ==============================================================================
# 1. SEGURIDAD Y CONFIGURACIÓN BÁSICA
# ==============================================================================

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Clave de desarrollo, SOLO se usa si DEBUG=True y no hay SECRET_KEY en el entorno.
# Marcada como insegura a propósito (prefijo django-insecure-) para que Django
# la señale si alguna vez termina usándose fuera de un entorno de desarrollo.
_INSECURE_DEV_SECRET_KEY = 'django-insecure-dev-key-sigct-rural-2025'

SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = _INSECURE_DEV_SECRET_KEY
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY debe estar definida por entorno cuando DJANGO_DEBUG no es "true". '
            'No hay fallback inseguro en producción.'
        )

_default_allowed_hosts = 'localhost,127.0.0.1' if DEBUG else ''
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', _default_allowed_hosts).split(',')
    if host.strip()
]

# ==============================================================================
# 2. APLICACIONES INSTALADAS
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de terceros
    'rest_framework',
    'corsheaders', 
    
    # Aplicaciones del Proyecto
    'api', 
    'users',
]

# ==============================================================================
# 3. MIDDLEWARE
# ==============================================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sigct_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigct_backend.wsgi.application'

# ==============================================================================
# 4. LÓGICA DE BASE DE DATOS (MIGRACIÓN A POSTGRESQL)
# ==============================================================================

# Verificamos si existe la variable DATABASE_URL (Docker la inyecta automáticamente)
database_url = os.environ.get('DATABASE_URL')

if database_url:
    # CASO A: Entorno Docker con PostgreSQL (Solvencia Técnica)
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # CASO B: Entorno Local (Git Bash / Terminal)
    # Si no hay URL, usamos la configuración manual de Postgres local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'sigct_db'),
            'USER': os.environ.get('DB_USER', 'user'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'password'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

# ==============================================================================
# 5. VALIDACIÓN DE CONTRASEÑAS
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================================================================
# 6. INTERNACIONALIZACIÓN Y ZONA HORARIA
# ==============================================================================

LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# 7. ARCHIVOS ESTÁTICOS
# ==============================================================================

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# 8. CONFIGURACIÓN CORS (INTEGRACIÓN FRONTEND)
# ==============================================================================

_cors_allowed_origins = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
if _cors_allowed_origins:
    CORS_ALLOWED_ORIGINS = _cors_allowed_origins
elif DEBUG:
    # Sin whitelist explícita: permitir todo SOLO en desarrollo local.
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = []

# ==============================================================================
# 9. ENDURECIMIENTO HTTP EN PRODUCCIÓN (inactivo en DEBUG para no romper local)
# ==============================================================================

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG